{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.pebblehost",
    "module": "plugin",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-0.1.0.jar",
          "url": "plugin-0.1.0.jar",
          "size": 28509,
          "sha512": "413060eeef897b8cff994a35d5d7f05c86704647ada02c371b8bf292a52150629e19416fb0e17f9b6ab93af0ed22762bec955b65c98ea5175664523df215bafe",
          "sha256": "e7f30bdaad84622233d9e96c452c697250482d026b55b0255e16091215edec73",
          "sha1": "b8e4e823750ac65af14547a81c85046cb67d145f",
          "md5": "c2aecca81c28817fddd4a193c7eab9e0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-0.1.0.jar",
          "url": "plugin-0.1.0.jar",
          "size": 28509,
          "sha512": "413060eeef897b8cff994a35d5d7f05c86704647ada02c371b8bf292a52150629e19416fb0e17f9b6ab93af0ed22762bec955b65c98ea5175664523df215bafe",
          "sha256": "e7f30bdaad84622233d9e96c452c697250482d026b55b0255e16091215edec73",
          "sha1": "b8e4e823750ac65af14547a81c85046cb67d145f",
          "md5": "c2aecca81c28817fddd4a193c7eab9e0"
        }
      ]
    }
  ]
}
